version: "3.8"

services:
  configserver:
    image: subodhbopche/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - subhbytes

  discoveryserver:
    image: subodhbopche/discoveryserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - subhbytes
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 4
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: subodhbopche/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - subhbytes
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

  loans:
    image: subodhbopche/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - subhbytes
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

  cards:
    image: subodhbopche/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - subhbytes
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

networks:
  subhbytes:
